### ISSUE TITLE
Code not compatible with Python3.9

### ISSUE THREAD

**Issue by jinnatar** [kanootoko/charge-power#1]
> File "/home/user/.local/pipx/venvs/charge-power/lib/python3.9/site-packages/charge_power/charge/print_charge.py", line 57, in <module>
    logfile: TextIO | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

The syntax you're using is introduced in Python3.10, so either the minimum required python version should be bumped in https://github.com/kanootoko/charge-power/blob/main/pyproject.toml#L17, or 3.9 compatible syntax should be used.

**Comment by kanootoko** [comment]
Thanks for a feedback!
That's true, I tested the code with Python 3.10 while implying for it to work with 3.9.
Will add `from __future__ import annotations` in a couple of hours.

**Comment by kanootoko** [comment]
@Artanicus Interesting thing. It seems that I have firstly uploaded package to PyPi and then added `annotations` import just before commiting and pushing. So, basically, PyPi version 0.1.0 contained different code rather than commit with version 0.1.0 here.

I have yanked it from PyPi and uploaded 0.1.1 to replace it.

Thanks again for opening issue.
